version: '3.8'

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  # FastAPI application
  api:
    image: syntaxsurge/autoblogger:latest
    command: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 8
    restart: on-failure
    logging: *default-logging
    environment:
      - SERVICE_NAME=api
    volumes:
      - ./host_logs:/app/logs
    env_file:
      - .env

  # Redis service
  redis:
    image: redis:latest
    command: redis-server --appendonly yes --bind 0.0.0.0
    ports:
      - "6379:6379"
    logging: *default-logging

  # Celery worker
  worker:
    image: syntaxsurge/autoblogger:latest
    command: celery -A main.celery_app worker --loglevel=info --concurrency=2 --pool=gevent
    restart: on-failure
    logging: *default-logging
    depends_on:
      - redis
    environment:
      - SERVICE_NAME=celery
    volumes:
      - ./host_logs:/app/logs
    env_file:
      - .env

  # Flower service for monitoring Celery workers
  flower:
    image: syntaxsurge/autoblogger:latest  # Use the same image as the worker
    command: celery -A main.celery_app flower
    environment:
      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH}
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB_INDEX}
    ports:
      - "5555:5555"
    depends_on:
      - worker

  # Nginx as the reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "7240:7240"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    depends_on:
      - api
    restart: on-failure
    logging: *default-logging
